INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (1, 0, 'تعاریف', 'list-ul', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (2, 1, 'اشخاص', 'user', 'person', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (3, 1, 'گروه ها', 'users', 'group', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (4, 1, 'محصولات', 'shopping-basket', 'product', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (5, 1, 'کدهای تخفیف', 'percent', 'offer', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (6, 1, 'امانتی ها', 'cubes', 'adjective', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (7, 1, 'بخش ها', 'th-large', 'section', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (8, 1, 'کتابخانه', 'university', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (9, 8, 'مدیریت کتب', 'book', 'book', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (10, 8, 'مدیریت امانات', 'tags', 'book-loan', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (11, 1, 'شمارنده', 'window-restore', 'counter', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (12, 0, 'کارت اشتراک', 'credit-card-alt', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (13, 12, 'مدیریت بسته ها', 'credit-card', 'package', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (14, 12, 'مدیریت شارژ', 'address-card', 'charge-package', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (15, 12, 'گزارش اصلاحات بسته ها', 'file-text', 'package-report', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (16, 0, 'باشگاه مشتریان', 'trophy', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (17, 16, 'تنظیمات باشگاه', 'bookmark', 'club', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (18, 16, 'گزارش امتیازات اعضا', 'file', 'club-log', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (19, 16, 'رتبه بندی اعضا', 'star', 'rating-club', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (20, 0, 'آموزش', 'pencil-square', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (21, 20, 'کلاس ها', 'pencil', 'course', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (22, 0, 'گزارشات', 'file-text', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (23, 22, 'گزارش تحلیلی', 'file-text', 'report', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (24, 22, 'گزارش بخش ها', 'file-text', 'game', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (25, 22, 'گزارش محصولات', 'file-text', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (26, 25, 'گزارش محصولات', 'file-text', 'factor', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (27, 25, 'گزارش فروشگاه', 'file-text', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (28, 25, 'گزارش اصلاحات محصولات', 'file-text', 'product-report', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (29, 22, 'گزارش حساب اشخاص', 'file-text', 'report-person', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (30, 22, 'گزارش بدهکاران', 'file-text', 'debt-person', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (31, 22, 'گزارش پرداخت', 'file-text', 'payment', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (32, 22, 'گزارش اصلاحات ورود و خروج', 'file-text', 'game-report', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (33, 8, 'گزارش اصلاحات کتابخانه', 'file-text', 'loan-report', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (34, 22, 'گزارش اصلاحات کد تخفیف', 'file-text', 'offer-report', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (35, 22, 'گزارش ارسال پیامک', 'file-text', 'sms-log', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (36, 0, 'نمودار ها', 'area-chart', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (37, 36, 'نمودار مراجعات', 'line-chart', 'chart', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (38, 0, 'پرسنل', 'user-circle', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (39, 38, 'حساب کاربری', 'user-plus', 'user', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (40, 38, 'گزارش تردد', 'file-text', 'user-activity', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (41, 38, 'مجوز دسترسی', 'check-square', 'user-group', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (42, 0, 'فرم نظرسنجی', 'comment', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (43, 42, 'مدیریت فرم ها', 'comments', 'vote', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (44, 42, 'گزارش نظرسنجی', 'file-text', 'response', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (45, 0, 'حسابداری', 'television', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (46, 45, 'کیف پول', 'minus-square', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (47, 46, 'کیف پول', 'square', 'wallet', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (48, 46, 'تنظیمات کیف پول', 'plus-square', 'wallet-setting', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (49, 45, 'مدیریت هزینه ها', 'database', 'cost', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (50, 45, 'روش پرداخت', 'calculator', 'payment-type', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (51, 0, 'پیکربندی', 'cog', '/', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (52, 51, 'عمومی', 'exclamation', 'global', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (53, 51, 'تعرفه', 'dollar', 'price', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (54, 51, 'پیامک', 'envelope', 'sms', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (55, 51, 'پشتیبانی', 'volume-control-phone', 'faq', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (56, 51, 'نصب و راه اندازی', 'spinner', 'setup', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (57, 1, 'ایستگاه/میز', 'braille', 'station', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (58, 12, 'گزارش اصلاحات شارژ', 'file-text', 'charge-report', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (59, 36, 'نمودار ساعات مراجعه', 'pie-chart', 'analytic-chart', NULL, NULL, 0);
INSERT INTO `menus` (`id`, `parent_id`, `name`, `icon`, `url`, `learn_url`, `details`, `display_order`) VALUES (60, 22, 'گزارشات اکسل', 'file-excel', 'excelreport', NULL, NULL, 0);
